### ISSUE TITLE
How can i change the gunicorn parameters on Docker image built by Azure Machine Learning service

### ISSUE THREAD

**Issue by zaidi-houda** [liupeirong/liupeirong.github.io#1]
I wanted to thank you for the description you made (https://liupeirong.github.io/amlDockerImage/) it helped me a lot. I used it to calibrate the gunicorn settings for APP service deployed by Azure Machine learning docker image. could you tell me on any version of Azureml-sdk this description is valid ? can you help me for this issue? [https://stackoverflow.com/questions/58752210/how-can-i-change-the-gunicorn-parameters-on-docker-image-built-by-azure-machine](url)

**Comment by liupeirong** [comment]
Azure ML docker images were not public when I wrote the blog. Now you can [extend those images](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-extend-prebuilt-docker-image-inference).
